//Banner code
var timer;
function Start_Timer(){
    timer = setInterval(banner, 5000);
}
function reset_timer(){
    clearInterval(timer);
    Start_Timer();
}

function banner(){
    var Checked = false;
    for (var i = 1; i <= 4; i++) {
        var checkbox = document.getElementById('radio' + i);
        if (checkbox.checked && Checked == false){
            var num = i + 1;
            if (num == 5){
                num = 1;
        }
            document.getElementById('radio'+num).checked = true;
            Checked = true;
        }
    }
    if (Checked == false){
        document.getElementById('radio1').checked = true;
    }
}

function Slide(num){
    var Checked = false;
    for (var i = 1; i <= 4; i++) {
        var checkbox = document.getElementById('radio' + i);
        if (checkbox.checked && Checked == false){
            var num = i + num;
            if (num == 5){
                num = 1;
            }
            if (num == 0){
                num = 4;
            }
            document.getElementById('radio' + num).checked = true;
            Checked = true;
        }
    }
    reset_timer();
}


//Search Code

function search(event){
    event.preventDefault();
        
    // Declare and Initialize every variable.
    var input = document.getElementById("searchbar").value;
    input = input.toUpperCase(); // Makes input capital.
    input = input.replace(/ /g, ""); // Remove input spaces.
    var result = "not_found";
    var NumOfResults = 0;
    
    // Var with more than 1 value are called arrays.
    var cond = [
        "INTRODUCTIONONCLIMATECHANGE", "CAUSESOFCLIMATECHANGE", "EFFECTSOFCLIMATECHANGE", 
        "GREENHOUSEEFFECT", "GLOBALWARMING", "SOLUTIONSFORCLIMATECHANGE", "ABOUT"
    ];
    var link = [
        "index.html", "Causes.html", "Effects.html", 
        "Greenhouse_Effect.html", "Global_Warming.html", "Solutions.html", "About_Us.html"
    ];
    var names = [
        "Introduction on Climate Change", "Causes of Climate Change", "Effects of Climate Change", 
        "Greenhouse Effect", "Global Warming", "Solutions for Climate Change", "About Us"
    ];
    
    if (input != ""){
        var WhichNum
        for(i=0; i<=cond.length-1; i++){
            if(cond[i].includes(input)){
            result = "found";
            NumOfResults++;
            WhichNum = i;
            }
        }

        event.preventDefault();  // Prevent Refresh after any message.
        if(NumOfResults == 1){
            // Redirect to another page if confirm == true.
            // \" are " in javascript.
            if(!window.location.href.includes(link[WhichNum])){
                if(confirm("Are you sure to go to \""+names[WhichNum]+"\" page?")){
                    window.location.href = link[WhichNum];
                }
            } else{
                alert("This is the page that you are looking for.");
            }
        }
        
        else if(result == "not_found"){
            alert("No Result Found");
        }
        
        else{
            var Result = document.getElementById("Result");
            var NewElement;
            Result.innerHTML = "";
            var description = [
                "Climate change refers to long-term alterations in temperature patterns, precipitation levels, wind patterns, and other aspects of Earth's climate system. It is primarily caused by human activities, particularly the burning of fossil fuels such as coal, oil, and gas, which release significant amounts of greenhouse gases into the atmosphere. These greenhouse gases....",
                "Climate change is a long-term alteration of the Earth's average weather patterns and temperature. It is primarily caused by human activities and natural processes. Here's how climate change happens:    Generating electricity and heat by burning fossil fuels causes a large chunk of global emissions. Most electricity is still generated by burning coal, oil, or gas....",
                "Climate change is one of the most pressing global challenges of our time, and its effects are becoming increasingly evident. From rising temperatures and sea levels to more frequent and severe extreme weather events, the consequences of climate change are far-reaching, impacting ecosystems, economies, and human societies worldwide. Here are 5 effects on climate change....",
                "The greenhouse effect is a good thing. It warms the planet to temperatures that keep life on earth, well, livable. Without it, the world would be more like Mars: a frozen, uninhabitable place. The problem is, the voracious burning of fossil fuels for energy is artificially amping up the natural greenhouse effect. The result? An increase in global warming that is....",
                "Since the Industrial Revolution, the global annual temperature has increased in total by a little more than 1 degree Celsius, or about 2 degrees Fahrenheit. Between 1880 the year that accurate record keeping began and 1980, it rose on average by 0.07 degrees Celsius (0.13 degrees Fahrenheit) every 10 years. Since 1981, however, the rate of increase has more than....",
                "Everyone can help limit climate change. From the way we travel to the electricity and water we use, we can make a difference. Start with these seven actions to help tackle the climate crisis: Transition to Renewable Energy: Shifting our primary energy sources from fossil fuels, such as coal and oil, to clean and renewable sources like solar, wind, hydro, and....",
                "Personal Details || Devesh Maniyanghattil | Class and Division: 7R | Email: deveshmaniyangatil@gmail.com | School: Habitat School Al Jurf || Ishan Ameen | Class and Division: 7R | Email: ishanameen2021@gmail.com | School: Habitat School Al Jurf || Shrivardhan | Class and Division: 7R | Email: shrivardhannayakuni@gmail.com | School: Habitat School Al Jurf"
            ]

            for(i=0; i<=cond.length-1; i++){
                if(cond[i].includes(input)){
                    NewElement = document.createElement('a');
                    NewElement.textContent = names[i];
                    NewElement.href = link[i];
                    Result.appendChild(NewElement);
                    Result.appendChild(document.createElement('br'));
                    NewElement = document.createElement('h5')
                    NewElement.textContent = description[i];
                    Result.appendChild(NewElement);
                    NewElement = null;
                }
            }
            
            input = document.getElementById("searchbar").value;
            document.getElementById("input").textContent = input;
            document.getElementById("SearchResult").style.display = "flex";
        }
    } else{}
}

function Close(){
    document.getElementById("SearchResult").style.display = "none";
}

// Navbar Code
var nav_toggle = document.getElementById("input_toggle");
var dropdown_toggle = document.getElementById("Input_DT");
var arrows = document.querySelector(".arrows");
var nav_auto = document.querySelector(".navigation-auto");
var nav_manual = document.querySelector(".navigation-manual");
var image = document.getElementById("image");

function check() {
    if (nav_toggle.checked == false) {
        dropdown_toggle.checked = false;
    }

    var slideHeight = image.clientHeight; // Get the height of the slides element
    var marginTop = slideHeight / 2 - 10 + "px";
    nav_auto.style.marginTop = slideHeight - 20 + "px";
    nav_manual.style.marginTop = slideHeight - 20 + "px";
    arrows.style.marginTop = marginTop;
}

setInterval(check, 100);

banner();
Start_Timer();
